apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: topic-karthik919
  namespace: openshift-gitops
spec:
  destination:
    namespace: kfka01
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - topic-values.yaml
    path: sharedcluster/karthik919
    repoURL: https://github.com/Karthik2618/kafka-test.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - Validate=false
