apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: topic-karthik257
  namespace: openshift-gitops
spec:
  destination:
    namespace: kafkatest2
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - topic-values.yaml
    path: kafka-topic-user-mgmt
    repoURL: https://github.com/maschind/kafka-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - Validate=false
